# ============================================================================
# FOLD THE QUR'AN-PROTEINS ON A FREE GPU (Google Colab) — self-contained.
#
# HOW TO RUN (2 minutes of setup, ~10 min total):
#   1. Go to  https://colab.research.google.com  ->  File -> New notebook
#   2. Runtime -> Change runtime type -> Hardware accelerator: GPU (T4) -> Save
#   3. Paste THIS ENTIRE FILE into one cell and press Run.
#
# It folds each short sura-protein AND a shuffled version of the same protein,
# then prints mean pLDDT (fold confidence, 0-100; >70 = confident, random ~ low).
#
# HONEST TEST: do the Qur'an-proteins fold clearly above their own shuffles?
# Our six controlled CPU runs predict NO. This puts that to the strongest oracle.
# A null is the finding.
# ============================================================================

import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "transformers", "accelerate"], check=True)

import torch, random, numpy as np
from transformers import AutoTokenizer, EsmForProteinFolding

tok = AutoTokenizer.from_pretrained("facebook/esmfold_v1")
model = EsmForProteinFolding.from_pretrained("facebook/esmfold_v1", low_cpu_mem_usage=True)
model = model.cuda().eval()
model.esm = model.esm.half()                      # half-precision language model (saves memory)
model.trunk.set_chunk_size(64)                    # chunked attention -> much lower GPU memory
torch.backends.cuda.matmul.allow_tf32 = True
import gc
MAXLEN = 200   # fold only suras up to this length first (raise once it's stable)

# ---- the 29 short sura-proteins (frequency-rank mapping; see make_proteins.py) ----
PROTEINS = {
  "sura108_Al-Kawthar": "LGLLPTEGLDLADVIINSAAITDVLGMILGGLGEDKVLALTRI",
  "sura112_Al-Ikhlas": "FAKVLAAKLMYLAAKLASSYASEAYVASEVAYVASEDGAKDNVLLMY",
  "sura103_Al-Asr": "VLAPSILGLALGQLGANELQILALLAHEGLSGVLVPSAVLLASLAMLRVRVLSVLTLAMFVRVLSVLTLASTI",
  "sura113_Al-Falaq": "FALPVHTITLANAFSGGISLLAFVSGGIRLQFLHLVFTVSGGILAGNLILRNELAPFYVSGGIMLQYLHLMQY",
  "sura106_Quraysh": "ALEALNFIEGLEALNKSIMAALAGRLKVLASENNAEPTYVLITKHLLATERLAHELTPSKSSGCVPVLSGKSSGLVN",
  "sura110_An-Nasr": "LHLCLKGSILAAKVLANRMVILERLAGLQEYLAVGNEYEGLAAKLNVLCLNQTMTMSYITDVLQRRNIKLGKDLGRVLTL",
  "sura114_An-Nas": "FALPVHTITLAGLQSADLAGLQLAKLAGLQSGGILAVQVLQLALGLQLAHEEVQVQNESYVILAGLQSGLACGAVLAGLQ",
  "sura111_Al-Masad": "RTREYLLTEAKTVRTSLLRGWPGKSLAKVSLDQTQESAWGLILHLRAKTVLSILRKMSLAALAMTTNECEYKLMTASGSQY",
  "sura105_Al-Fil": "LASRIDENNPAITDTLSMLTLANEALASECPADEYKSNERVAEAVLIQAPAEKSTEILLTLTEARISEKSTMCLIASGQCEANCPAKSDPSNSLDVA",
  "sura109_Al-Kafirun": "FAELLEKLLADLNIVGALLPTYSLRPTYVGVALLGRSPLTYVGSLLPTYVALLGLPLTYSLPTYRSVALLGRSPLTYVGSLLPTYADSYEGDSVAEYEG",
  "sura094_Ash-Sharh": "LASGGIMADSYIDVVVPGLPGDVEIDLAHELGFVDKIDVINPGLADHDIDNLGSPLAPQIEQILLGSPLAPQIEQILNLHLNIRRNLGSTVLAWITDNLIRT",
  "sura107_Al-Maun": "LILERLAHEEDHTTLAYEGNHADLAHEEYPLAERESVALEMVPAWTPLSLASQDEGNVEAAASSAEGLAHEGKSPGSALRKSQLKVGLAHEGKSEILKVGVESGPVGLASLPVG",
  "sura097_Al-Qadr": "LGLLGEAGLKNEAEAALAFYIVSLLYILDSLAEAALAFYIAEAALAFYILEISGLANGKIRGEALASALEDAVLAIVMNEKLTLHGITKSSGDALSIQALSKEMRWSTAPLANCI",
  "sura102_At-Takathur": "LAKLDSLARDLIIMRWEIRSLASFLTIDALQVNRPASVGISDALQVNRPASVGDALAVRPASVGPASLAEFEGARIVGLACMESISARIVGKLPEGLAEFEGISARQLAGEVSEHPGLAGPES",
  "sura104_Al-Humazah": "VEAADAKSEAASEALAHECSPSLALVPYYKEMQTLGSLAKLLAYKDALAEGTHGNELAMTSAVSLLYILDSLLAMTSAGLILAAKLASVFYALARERTAPPAWLALNEYALGKLPAEKSSVSYANEPSYSSYYA",
  "sura001_Al-Fatihah": "TQSLAAKLAIMSGLAIMESLAMSYAAKITLAPLASEGLAIMSGLAIMESSLADEVSLAYEGLELDGPTYVLELDGQRPEGLKYGLLASILTLASQRFESSILTLAHEGLGPSRPAEKSREILASRVVTPAEKSVALLAVLAEG",
  "sura099_Az-Zalzalah": "LHLEAEARLALIVEAELAKLVLLICRLALIVLIFLAKLVFLALALGQLGSLAKLEVSEHRMYILLTLIKLTLGITDLVMWAKLEVSEHESYILAGLQLGRLRLAEIVLLPSLAKSNSGEPSASIFLAHIALEILEIKVSGEPSASIFLAHIAGILEIK",
  "sura101_Al-Qariah": "LAFLIPASLLAFLIPAVSLLYILDSLLAFLIPAEVSEDVGLAGLQDLANILGLASTIVIVRDVGLACTLADLAPKGLASGNVGNLSLSGIFARSVLEEGKNKVNEPEGAILVEAVLSLSGLNRSVLEEGKNLSKKLVEAVSLLYILDSLKEKGLIMLSEA",
  "sura095_At-Tin": "VLAREGVLAEERVGVTVIQEGEGVKHLLATAYLALSEGAFYLAFGLLALGQLGNELMQGRFVESISIYYGLKLQNAQLNAEGLALLAHEGLSGVLVPSAVLLASLAMLRNAKSLCIREISSGVGNSLEDHTDTPYTLAYEGLAEQLAAKTLMDSLAMLDSEG",
  "sura093_Ad-Duha": "VLAVMWVLAAEALHLQCWSLVYPDITDVSLFAWVAALLIALEIADSGLALVAWVAQVNEPTEDITDNRIVWLASECYDERESLNLVWVVCYDVLALNKYWVVCYDPLEALNLRGWNLSLLAERESNALRFKIVLSLLAQLEANALRGKIVLSLTGPSAITDNMYI",
  "sura100_Al-Adiyat": "VLAPLYELRVTMLNLASVIELRFYMLNLASREILRSTMLNLIIGTKGFPLNVQTGTKCSPLLGLALGQLGAITKADGVYVLGKPAWHADAGKEYVLGKAMTLALEIAGYEYLNALEPASLHLTPIISLNELAFTVIVMSASLNELASYVILGITKSTKSEVSEHALTEI",
  "sura091_Ash-Shams": "VLAGSQVVMLKLVLAFSILHLRALKLVLAGKLILHLCALKLVLAAEALHLERGLKLVLAQSLKVSLTGLKLVLALIVVSLTMLKLVGNQVSLQVLKLNLAKSKLNCVIKLVRFVLKLFYLNAMSGEDLKLVFYLLTSGYQLKLDHTRISVYTTRVLKLLHLGTPILGFLKLNFLAAKSIQVALAAKGLFALAAKVQFELKLNDHTVKNPFIVKLNYSYSPAEKSITKSTHGTKSNQVLKLVALELLNPFTLKL",
  "sura086_At-Tariq": "VLAQSLKVLATLIFVSLLYILDSLLATLIFLAGCSLAILFTLGDAGNQASLPAEKLMLNDNAEGDILALGQLGSSLAFLAFSGSLKYLNFELICSGTEGLASATVLARILETLGKPAWICPKAFLYIEVSRTAWLAQILEINSLAKSGFVAVALGLSIVLAQSLKHLRLAICPVLALIVHLRLASYPLGKAFVANSAVSLKVTLAKEALGKSEDEYVGDEYLVLDEYDEYLNSKALADLNIEGLSKAKSIVEYL",
  "sura096_Al-Alaq": "LFILTLQSITDLAHELAFLAFLALGQLGSGPAFLFILVITDLALDISLAHEPASTLAFASPASLALGQLGSLASEPASDALLGLALGQLGAETRWLGILKLQRRGWLGLAWITDLAICPWLILERLAHEEGKWPTYLLHLSAWLILERLGDLGPAWLAKYWLVLSITLARFVWLILERLGDHTVRVAWLASEPASTLGLAAKEIWDALAEGASEGRKAGQNPLTLAGLSEAGLSEADLHTALLTEANAEYPGLYEKQGYPLAETLGEADALALRTPKVLQCYVLFRIT",
  "sura087_Al-Ala": "QTMLQSITDLALPAWLAHELAFNQVWVLAHEFYINKYWVLAHELLICLASIPWNCPAKRILKLMVWQGFIEDNALRGQWLALSLGLKLAAKLGKEPASLACKIVSLELNWVGEQIDAAEQIWNHDILGGNPRLAHDIWQEHDISGELGWVERCGTKLLALGFWLAHEESAWLAGLILADTIWISALESVRNEKLVALEMEWFYLNAMSGREDWVHDILQSITKNSAWTARVIIVGLAMELALAYGELVLALLIALEIVLTFWLGKHLANELASMNLALVAWSMNLTILKESVSVQW",
  "sura092_Al-Layl": "VLAAEALHLERGWVLAGKLILHLRCAWVSLLAFLAHDIVLALGIWLGQPEDSAGRWNLSLSGLPTWVLRFWVSYFTLAMQGWNQGEQIKAAEQIWVLSLSGTLAVLQRRGWVDHTTLAMQGWNQGEQIKAAPQIWVSLERGEPGKSLAKLHLRIYWLGPAEGLAAKYWVLGAGLAALLIAVLALVAWNLGHIRDSGLILRADWALESALKLLALLALGFWLAHEDHTVRVAWVQECGTKLLALRFWLAHEEVRESLAKEREDWVSLALMYPGYKSGGPSARCEWLALLTRRLKVCKITKLALPAWVAQVNEIVW",
  "sura082_Al-Infitar": "LHLLAQSLKLGNTIRVLHLLADVLDTLGRIIRVLHLLATMLINCIRVLHLLAFTVITPIIRPASRGNQSLFYSRVLLIRELLEKLLALGQLGSLRIDTITDLADIESLAHELAFDNQVLDNPYADNELESVIASLGLKIDTDDALTARDHTVGTLAYEGVLGPAEDSAMLNDEGDILSLDLRTEGEPASVGSLRNPAVGLGLALTILIANEGPESVLGLANCLIANECMESESAVGKLEVSLAYEGVSLKSPGKLTRLETEGVSLLYILDSLEVSLAYEGISSLLYILDSLEVSLAYEGEVSALRSADGNQAGNQGEELVLALSIEVSEHAAK",
  "sura090_Al-Balad": "ALLFQSTKHLLATAYVLGRMATKHLLATAYVVLAYVSLVAYAFYLAFGLLALGQLGNEDTYLEMQTLGAGEFYIPAEKLMYEFVALKADRSLALATYLLEMQTLGASEIKLMYLASGCPAAKPEGEGVAQLGLVGNREGVKYEGLKLAGCYEGNALLFRMSLAPFTAVSLLYILDSLLAPFTANDIFTALVLTPLSNEEVSHESQRTAERESLHLSFITALVSQDEGLHLSRITAISDLGSGLAHEGLSGVLVRVLSVLTLASTIVRVLSVLTLASIMSALVAEDLSMLTLASESGAVLAHEGDNIVLTLELRGLKSLSMLTLASGLSAPAEKSGLISVSYA",
}

def fold_pdb(seq):
    ids = tok([seq], return_tensors="pt", add_special_tokens=False)["input_ids"].cuda()
    with torch.no_grad():
        out = model(ids)
    pdb = model.output_to_pdb(out)[0]
    del ids, out; gc.collect(); torch.cuda.empty_cache()   # free memory between folds
    return pdb

def mean_plddt(pdb):
    v = [float(l[60:66]) for l in pdb.splitlines()
         if l.startswith("ATOM") and l[12:16].strip() == "CA"]
    return sum(v)/len(v) if v else float("nan")

def shuffle(s):
    l = list(s); random.seed(0); random.shuffle(l); return "".join(l)

print(f"{'sura':24}{'len':>5}{'pLDDT real':>12}{'pLDDT shuffled':>16}")
R, S = [], []
for name, seq in sorted(PROTEINS.items(), key=lambda x: len(x[1])):
    if len(seq) > MAXLEN:           # skip the longest for now (raise MAXLEN later)
        continue
    try:
        pr = mean_plddt(fold_pdb(seq))
        ps = mean_plddt(fold_pdb(shuffle(seq)))
    except RuntimeError as e:        # catch GPU OOM on a single long protein, keep going
        print(f"{name:24}{len(seq):>5}   skipped: {str(e)[:38]}")
        gc.collect(); torch.cuda.empty_cache(); continue
    R.append(pr); S.append(ps)
    print(f"{name:24}{len(seq):>5}{pr:>12.1f}{ps:>16.1f}")

print(f"\nMEAN pLDDT   real = {np.mean(R):.1f}    shuffled = {np.mean(S):.1f}    (>70 confident, >85 high)")
print("Real >> shuffled AND high  => a signal worth chasing (Route A search next).")
print("Real ~ shuffled, or both low => honest null, exactly as our six CPU runs predicted.")
